em_sys/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import depart, user, admin, login, task, order, chart

urlpatterns = [

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/edit/', depart.depart_edit),
    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/add/modelform/', user.user_add_modelform),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),
    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),
    # 登录
    path('login/', login.login),
    # 注销
    path('logout/', login.logout),
    # 生成验证码
    path('image/code/', login.image_code),
    # 初试Ajax
    path('task/list/', task.task_list),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    # 接收用户订单请求，并保存
    path('order/add/', order.order_add),
    # 删除订单
    path('order/delete/', order.order_delete),
    # 在修改订单弹窗中显示内容
    path('order/detail/', order.order_detail),
    # 保存订单编辑的内容
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/',chart.chart_bar),
]

app01/models.py
from django.db import models


class Admin(models.Model):
    username = models.CharField(verbose_name="姓名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=32)

    # 当外键连接的时候，返回to_field对应id的name
    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='部门名称', max_length=32)

    # 当别的表的外键to_field="title"的时候，返回这个对象的“title”
    def __str__(self):
        return self.title


class Employee(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name='入职时间')
    # 通过外键将depart和表Department相关联，约束depart列只能用Department中已有的id
    # -to 相关联的表
    # -to_filed 相关表中相关的列
    # django会在生成的表中自动将depart列的名称写为depart_id
    # 如果某个部门被删除
    # 1、将员工删除、联级删除Em
    # depart = models.ForeignKey(to="Department", to_field="id", on_delete=models.CASCADE)
    # 2、将相关的列置空
    depart = models.ForeignKey(verbose_name='部门', to="Department", to_field="id", null=True, blank=True,
                               on_delete=models.SET_NULL)

    # 在Django中为表添加约束
    gender_choices = (
        (1, "男"),
        (2, "女")
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, default=1)


class Num_manage(models.Model):
    numbers = models.CharField(verbose_name="电话号码", max_length=11)
    price = models.DecimalField(verbose_name="价格", max_digits=10, decimal_places=2, default=0)
    level_choice = (
        (1, "普通"),
        (2, "稀有"),
        (3, "超稀有")
    )
    level = models.SmallIntegerField(verbose_name="稀有度", choices=level_choice, default=1)
    state_choice = (
        (1, "已占用"),
        (2, "未占用")
    )
    state = models.SmallIntegerField(verbose_name="占用状态", choices=state_choice, default=2)


class Tasks(models.Model):
    """任务"""
    level_choice = (
        (1, '紧急'),
        (2, '重要'),
        (3, '临时'),
    )
    title = models.CharField(verbose_name="标题", max_length=64)
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choice, default=2)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to=Admin, to_field="id", on_delete=models.CASCADE)  # 联级删除


class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=32)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")
    statu_choices = [
        (1, "已支付"),
        (2, "未支付"),
    ]
    statu = models.SmallIntegerField(verbose_name="状态", choices=statu_choices, default=2)
    uid = models.ForeignKey(verbose_name="管理员id", to=Admin, to_field="id", on_delete=models.CASCADE)

app01/views/admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm,AdminResetModelForm


def admin_list(request):
    # 从浏览器中获取session，检查用户是否登录
    info = request.session.get('info')
    if not info:
        return redirect('/login/')

    # 用户查询功能
    data_dict = {}
    # 有值拿值没值拿字符串
    search = request.GET.get('search', '')
    if search:
        # 将"search"中含有name的数据筛选出来
        data_dict["username__contains"] = search
    # 自己用queryset配置搜索条件，然后传入Pagination类
    queryset = models.Admin.objects.filter(**data_dict).order_by("id")
    page_object = Pagination(request, queryset)
    username = page_object.page_queryset
    page_string = page_object.html()

    context = {
        "username": username,  # 每一页展示的数据
        'name_search': search,  # 用户查询的内容（用来传回html，显示在搜索框中）
        "page_string": page_string  # 用来生成分页栏
    }

    return render(request, "admin_list.html", context)


def admin_add(request):
    # 添加管理员
    title = '新建管理员'

    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title, 'action': 'admin/add/'})


def admin_edit(request, nid):
    # 通过url编辑管理员信息
    row_object = models.Admin.objects.filter(id=nid).first()
    # 让标题后面加上当前修改信息的对象的username
    title = '编辑管理员信息' + '-{}'.format(row_object.username)
    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        if not row_object:
            return render(request, "error.html", {'error': "该用户不存在"})
        return render(request, "change.html", {'form': form, "title": title})
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    title = '重置密码' + '-{}'.format(row_object.username)
    if request.method == 'GET':
        form = AdminResetModelForm(instance=row_object)
        if not row_object:
            return render(request, "error.html", {'error': "该用户不存在"})
        return render(request, "change.html", {'form': form, "title": title})
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})

app01/views/chart.py
from django.http import JsonResponse
from django.shortcuts import render, redirect


def chart_list(request):
    return render(request, 'chart_list.html')


def chart_bar(request):
    """构造柱状图数据"""
    legend = ["销量", "业绩"]
    series = [
        {
            "name": "销量",
            "type": 'bar',
            "data": [5, 20, 36, 10, 10, 20]
        },
        {
            "name": "业绩",
            "type": 'bar',
            "data": [20, 15, 38, 10, 12, 15]
        }
    ]
    x_list = [
        '衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子'
    ]

    result = {
        "status": True,
        "data": {
            'legend': legend,
            'series': series,
            'x_list': x_list,
        }
    }

    return JsonResponse(result)

app01/views/depart.py
from django.shortcuts import render, redirect
from app01 import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from app01.utils.form import UserModelForm, UserEditModelForm
from app01.utils.Pagination import Pagination


def depart_list(request):
    """部门列表"""
    department = models.Department.objects.all()

    return render(request, 'depart_list.html', {'departments': department})


def depart_add(request):
    if request.method == "GET":
        return render(request, "depart_add.html")
    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart/list/")


def depart_delete(request):
    if request.method == "GET":
        nid = request.GET.get("nid")
        if nid:
            models.Department.objects.filter(id=nid).delete()
            return redirect("/depart/list/")
        return render(request, "depart_delete.html")
    title = request.POST.get("title")
    models.Department.objects.filter(title=title).delete()
    return redirect("/depart/list/")


def depart_edit(request):
    if request.method == "GET":
        otitle = request.GET.get("otitle")
        if otitle:
            return render(request, "depart_edit.html", {"otitle": otitle})
        return render(request, "depart_edit.html")
    o_title = request.POST.get("title_origin")
    n_title = request.POST.get("title_new")

    exit = models.Department.objects.filter(title=o_title).update(title=n_title)

    if exit:
        models.Department.objects.filter(title=o_title).update(title=n_title)
        return redirect("/depart/list/")

app01/views/login.py
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.utils.form import LoginForm
from app01.utils.code import check_code
# io 用于生成和调用内存中的内容
from io import BytesIO


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    form = LoginForm(request.POST)
    if form.is_valid():
        # 验证码的校验,获取到code的同时,将code从字典中踢出,以便下面在数据库中根据用户名和密码筛选用户
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')
        if user_input_code.upper() != code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})
        # 从网页中传入的数据是一个字典
        # {"name":"xxx","password":"xxx"}
        # 所以可以直接将获取到的字典用filter在数据库中进行筛选，前提！！！是在LoginForm中定义的字段名和数据库中的字段名一致
        login_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not login_object:
            # 添加错误信息，前面的属性是错误信息出现的位置对应的字段名
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        # 登录成功
        # 这一段就是通过request_session语句，将键值对' info '= {"name": login_object.username,"password": login_object.password}存贮到浏览器的session中
        request.session['info'] = {"id": login_object.id, "username": login_object.username,
                                   "password": login_object.password}
        # session的内容七天内有效
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect('/admin/list/')
    return render(request, 'login.html', {'form': form})


def image_code(request):
    # 通过check_code函数生成图片验证码
    img, code_string = check_code()
    # 将创建的图片验证码中的文本存到session中,以便后续获取
    request.session['image_code'] = code_string
    # 给session设置超时,不能让验证码一直有效
    request.session.set_expiry(60)
    # 在内存中创建一个文件，并且将图片写入该文件中
    stream = BytesIO()
    img.save(stream, format='PNG')
    # 从内存中读取图片
    return HttpResponse(stream.getvalue())


def logout(request):
    request.session.clear()
    return redirect('/login/')

app01/views/order.py
from django.http import JsonResponse
from django.shortcuts import render
from app01.utils.form import OrderModelForm
from datetime import datetime
import random
from app01 import models
from app01.utils.Pagination import Pagination
from django.views.decorators.csrf import csrf_exempt


def order_list(request):
    form = OrderModelForm(data=request.GET)
    data_dict = {}
    title = request.GET.get('title', '')
    if title:
        data_dict['title__contains'] = title
    queryset = models.Order.objects.filter(**data_dict).order_by('-id')
    page_object = Pagination(request, queryset)
    order = page_object.page_queryset
    page_string = page_object.html()
    context = {
        "order": order,
        "title": title,
        "page_string": page_string,
        "form": form,
    }
    if request.method == 'GET':
        return render(request, "order_list.html", context)


def order_add(request):
    print("order_add后台接收到的信息是：")
    print("info.in:" + str(request.session.get('info').get('id')))
    """ajax请求创建订单"""
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        # instance后面的字段名必须是数据库中字段名的真实字段名（例如uid的真实字段名是uid_id,因为uid是外键）
        form.instance.uid_id = request.session['info']['id']
        # 创建订单的时候自动生成订单号添加到数据库中
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
        # 直接把当前登录的管理员当作该订单的管理员
        form.save()
        # return HttpResponse(json.dumps({"status":True}))
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})


def order_delete(request):
    delete_id = request.GET.get('dlt_id')
    print(delete_id)
    delete_obj = models.Order.objects.filter(id=delete_id).first()
    print(delete_obj)
    if not delete_obj:
        return JsonResponse({'status': False, "error": "数据不存在1"})
    models.Order.objects.filter(id=delete_id).delete()
    return JsonResponse({'status': True})


@csrf_exempt
def order_detail(request):
    order_id = request.GET.get('edt_id')
    order_obj = models.Order.objects.filter(id=order_id).first()
    if not order_obj:
        return JsonResponse({"status": False, "errors": "数据不存在2"})
    result = {
        "status": True,
        "data": {
            "title": order_obj.title,
            "price": order_obj.price,
            "statu": order_obj.statu,
        }
    }
    return JsonResponse(result)


def order_edit(request):
    order_id = request.GET.get('edt_id')
    order_obj = models.Order.objects.filter(id=order_id).first()
    if not order_obj:
        return JsonResponse({"status": False, "errors": "订单不存在"})
    form = OrderModelForm(data=request.POST, instance=order_obj)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, "errors": form.errors})

app01/views/task.py
import json
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from app01.utils.form import TaskModelForm


def task_list(request):
    form = TaskModelForm()
    return render(request, 'task_list.html', {"form": form})


@csrf_exempt
def task_add(request):
    print(request.GET)
    print(request.POST)
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {"status": True}
        # json.dumps()将内容转换为json格式
        return HttpResponse(json.dumps(data_dict))
    print(type(form.errors))
    data_dict = {"status": False, "errors": form.errors}
    # ensure_ascii = False 将
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))
    # 将form中的错误信息（ErrorDict格式）转换为json格式，传回前端浏览器
    # data_dict = {"status": False, 'error': form.errors.as_json()}
    # return HttpResponse(json.dumps(data_dict))

app01/templates/admin_list.html
{% extends "layout.html" %}

{% block content %}
    <div style="margin-bottom: 20px" class="clearfix">
        <a href="/admin/add/" class="btn btn-primary">新建管理员</a>
        <form method="get" style="width:300px;float: right">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search for..." value="{{ search }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Go!</button>
                </span>
            </div><!-- /input-group -->
        </form>
    </div>
    <div>
        <div class="panel panel-default">

            <div class="panel-heading">管理员列表</div>

            <table class="table table-bordered" style="table-layout: fixed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in username %}
                <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.username }}</td>
                        <td>*******</td>
                        <td>
                            <a href="/admin/{{ obj.id }}/reset/">重置密码</a>
                        </td>
                        <td>
                            <a class="btn btn-success btn-sm" href="/admin/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-sm" href="/admin/{{ obj.id }}/delete/">删除</a>
                        </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="clearfix">
        <nav aria-label="Page navigation" class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    {# 新建订单按钮/搜索框 #}
    <div class="container clearfix">
        <input type="button" placeholder="新建订单" class="btn btn-primary btnAdd" value="新建订单（js）">
        <input type="button" placeholder="新建订单" class="btn btn-primary" value="新建订单" data-toggle="modal"
               data-target="#myModal">
        <form method="get" style="width:300px;float: right">
            <div class="input-group">
                <input type="text" name="title" class="form-control" placeholder="Search for..." value="{{ title }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Go!</button>
                </span>
            </div><!-- /input-group -->
        </form>
    </div>
    {#  表格内容  #}
    <div style="margin-top:20px">
        <div class="panel panel-default">

            <div class="panel-heading">订单列表</div>

            <table class="table table-bordered" style="table-layout: fixed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>商品名称</th>
                    <th>价格</th>
                    <th>订单状态</th>
                    <th>订单管理员</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in order %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_statu_display }}</td>
                        <td>{{ obj.uid.username }}</td>
                        <td>
                            <input row_id="{{ obj.id }}" type="button" class="btn btn-success btnAdd" value="编 辑">
                            {# 因为id属性只能有一个，如果用的是id="btnDelete"则只会有一个按钮生效，别的按钮都不能生效 #}
                            {# 所以为了让所有的按钮都生效，只能使用class="btnDelete" #}
                            <input row_id="{{ obj.id }}" type="button" class="btn btn-danger btnDelete" value="删 除">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {#  分页栏  #}
    <div class="clearfix">
        <nav aria-label="Page navigation" class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
    {#  添加订单/编辑订单 对话框  #}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="formAdd">
                        {% csrf_token %}
                        {% for obj in form %}
                            <div style="margin-bottom:20px ">
                                <label>{{ obj.label }}</label>
                                {{ obj }}
                                <span class="error_msg" style="color:red;position:absolute;"></span>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id='btnSave' type="button" class="btn btn-primary">保存</button>
                </div>
            </div>
        </div>
    </div>
    {#  删除警告框  #}
    <div id="deleteModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="alert alert-danger alert-dismissible fade in clearfix" role="alert" style="margin:0">
                    <h4>确认删除</h4>
                    <p>是否确定删除所有相关数据？任何删除的数据都不可挽回！</p>
                    <p style="float:right">
                        <button id="btnDelete_confirm" type="button" class="btn btn-danger">确 认</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    </p>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}
{% block js %}
    <script type="text/javascript">
        var delete_id;
        var edit_id = undefined;
        // 当页面框架加载完之后自动执行这个代码
        $(function () {
            bindBtnAddOrderEvent();
            bindBtnSaveOrderEvent();
            bindBtnDeleteOrderEvent();
            bindBtnDeleteOrderEvent_confirm();
        })
        {#在bootstrap文档中有提到，通过js的方式实现弹窗#}
        // 弹出（新建/修改）弹窗
        function bindBtnAddOrderEvent() {
            $(".btnAdd").click(function () {
                edit_id = $(this).attr("row_id");
                console.log("edit_id:" + edit_id);
                if (edit_id) {
                    // 为了清空之前有编辑过某条数据之后edit_id被赋的值
                    $('#formAdd')[0].reset();
                    $("#myModalLabel").text('编辑订单');
                    $('#myModal').modal('show');
                    console.log("当前编辑的edit_id是：" + edit_id)
                    doEdit();
                } else {
                    // 为了清空之前有编辑过某条数据之后edit_id被赋的值
                    $('#formAdd')[0].reset();
                    $('#myModal').modal('show');
                    $("#myModalLabel").text('新建订单');
                    console.log("新建的edit_id是：" + edit_id);
                }
            })
        }

        // 确认（新建/编辑）保存
        function bindBtnSaveOrderEvent() {
            $("#btnSave").click(function () {
                {#如果上次有错误信息，在输入框正确填写之后，清空错误信息#}
                $(".error_msg").empty();
                if (edit_id) {
                    $.ajax({
                        url: '/order/edit/?edt_id=' + edit_id,
                        type: 'POST',
                        data: $('#formAdd').serialize(),
                        dataType: "JSON",
                        success: function (res) {
                            if (res.status) {
                                alert("修改成功")
                                // 清空表单中的数据
                                $('#formAdd')[0].reset();
                                // 隐藏对话框
                                $('#myModal').modal('hide');
                                // 刷新当前页面
                                location.reload();
                            } else {
                                $.each(res.errors, function (k, v) {
                                    {# modelform生成标签的时候会自动生成一个id="id_字段名",这就可以进行一下的字符串拼接#}
                                    $('#id_' + k).next().text(v[0]);
                                })
                            }
                        }
                    })
                } else {
                    // 新建订单的保存
                    $.ajax({
                        url: '/order/add/',
                        type: 'POST',
                        data: $('#formAdd').serialize(),
                        dataType: "JSON",
                        success: function (res) {
                            if (res.status) {
                                alert("添加成功")
                                // 清空表单中的数据
                                $('#formAdd')[0].reset();
                                // 隐藏对话框
                                $('#myModal').modal('hide');
                                // 刷新当前页面
                                location.reload();
                            } else {
                                $.each(res.errors, function (k, v) {
                                    {# modelform生成标签的时候会自动生成一个id="id_字段名",这就可以进行一下的字符串拼接#}
                                    $('#id_' + k).next().text(v[0]);
                                })
                            }
                        }
                    })
                }
            })
        }

        // 弹出删除弹窗
        function bindBtnDeleteOrderEvent() {
            $(".btnDelete").click(function () {
                $("#deleteModal").modal('show');
                delete_id = $(this).attr("row_id");
                console.log('删除的id是：' + delete_id);
            })
        }

        // 确认删除
        function bindBtnDeleteOrderEvent_confirm() {
            $("#btnDelete_confirm").click(function () {
                $.ajax({
                    url: '/order/delete/',
                    type: 'GET',
                    data: {
                        dlt_id: delete_id,// 传回的url：order/delete/?dlt_id=delete_id
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("删除成功");
                            $("#deleteModal").modal("hide");
                            location.reload();
                        } else {
                            alert("删除失败，数据不存在。");
                            $("#deleteModal").modal("hide");
                            location.reload();
                        }
                    }
                })
            })
        }

        // 从数据库中获取当前edit_id对应的id，然后将所有数据展现在输入框中
        // 因为这个函数没有绑定事件，而是通过bindBtnAddOrderEvent()调用函数，所以不添加到开头的function中，以免自动执行
        function doEdit() {
            $.ajax({
                url: '/order/detail/',
                type: "GET",
                data: {
                    edt_id: edit_id,
                },
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        $.each(res.data, function (name, value) {
                            $("#id_" + name).val(value);
                        })
                        $('#myModal').modal("show");
                        console.log(res)
                    } else {
                        alert(res.errors);
                    }
                }
            })
        }
    </script>
{% endblock %}

app01/templates/user_list.html
{% extends "layout.html" %}
{% block content %}
    <div style="margin-bottom: 20px" class="clearfix">
        <a href="/user/add/" class="btn btn-primary">新建用户</a>
        <a href="/user/add/modelform" class="btn btn-primary">新建用户(modelform)</a>
        <form method="get" style="width:300px;float: right">
            <div class="input-group">
                <input type="text" name="name" class="form-control" placeholder="Search for..." value="{{ name }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Go!</button>
                </span>
            </div><!-- /input-group -->
        </form>
    </div>
    <div>
        <div class="panel panel-default">

            <div class="panel-heading">用户列表</div>

            <table class="table table-bordered" style="table-layout: fixed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>账户余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in employee %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time | date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-success btn-sm" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-sm" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="clearfix">
        <nav aria-label="Page navigation" class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}